### ISSUE TITLE
SafeInt Overflow

### ISSUE THREAD

**Issue by AdamE87** [Sicos1977/IFilterTextReader#13]
SafeInt Overflow on reading any PDF:

Trace:
<code>
   at IFilterTextReader.NativeMethods.IPersistStream.Load(IStream pStm)
   at IFilterTextReader.FilterLoader.LoadAndInitIFilter(Stream stream, String extension, Boolean disableEmbeddedContent, String fileName, Boolean readIntoMemory) in T:\Software\IFilterTextReader-1.5\IFilterTextReader-1.5\IFilterTextReader\FilterLoader.cs:line 160
   at IFilterTextReader.FilterReader..ctor(String fileName, String extension, Boolean disableEmbeddedContent, Boolean includeProperties, Boolean readIntoMemory, FilterReaderTimeout filterReaderTimeout, Int32 timeout) in T:\Software\IFilterTextReader-1.5\IFilterTextReader-1.5\IFilterTextReader\FilterReader.cs:line 195
   at IFilterTextViewer.MainForm.SelectButton_Click(Object sender, EventArgs e) in T:\Software\IFilterTextReader-1.5\IFilterTextReader-1.5\IFilterTextViewer\MainForm.cs:line 139
The text associated with this error code could not be found.

Safe Int Overflow 0x80048605
</code>

This occurs at IStreamWrapper

**Comment by Sicos1977** [comment]
I will look into it next werk.On vacation at the moment


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: AdamE87 <notifications@github.com> 
Datum: 02-02-2016  11:13  (GMT+01:00) 
Aan: Sicos1977/IFilterTextReader <IFilterTextReader@noreply.github.com> 
Onderwerp: [IFilterTextReader] SafeInt Overflow (#13) 

SafeInt Overflow on reading any PDF:

Trace:



   at IFilterTextReaderNativeMethodsIPersistStreamLoad(IStream pStm)

   at IFilterTextReaderFilterLoaderLoadAndInitIFilter(Stream stream, String extension, Boolean disableEmbeddedContent, String fileName, Boolean readIntoMemory) in T:\Software\IFilterTextReader-15\IFilterTextReader-15\IFilterTextReader\FilterLoadercs:line 160

   at IFilterTextReaderFilterReaderctor(String fileName, String extension, Boolean disableEmbeddedContent, Boolean includeProperties, Boolean readIntoMemory, FilterReaderTimeout filterReaderTimeout, Int32 timeout) in T:\Software\IFilterTextReader-15\IFilterTextReader-15\IFilterTextReader\FilterReadercs:line 195

   at IFilterTextViewerMainFormSelectButton_Click(Object sender, EventArgs e) in T:\Software\IFilterTextReader-15\IFilterTextReader-15\IFilterTextViewer\MainFormcs:line 139

The text associated with this error code could not be found

Safe Int Overflow 0x80048605



This occurs at IStreamWrapper

**Comment by AdamE87** [comment]
Reading the file into memory resolves this....happy to close

**Comment by Sicos1977** [comment]
Can hou still send me the file that is giving the error so that i can find out where it comes from ?

**Comment by AdamE87** [comment]
It did it on every file but i'll attach one I had a problem with...
[Scrum_Guide.pdf](https://github.com/Sicos1977/IFilterTextReader/files/115493/Scrum_Guide.pdf)

**Comment by Sicos1977** [comment]
Strange that you got of in evert file.
I look into it next week
