### ISSUE TITLE
Index out of bounds reading a pdf document

### ISSUE THREAD

**Issue by bodker-68** [Sicos1977/IFilterTextReader#23]
Hello,

I've come across some pdf documents that causes an "_Index was outside the bounds of the array_" exception in the FilterReader:

`   at IFilterTextReader.FilterReader.Read(Char[] buffer, Int32 index, Int32 count) in C:\Users\jbodker\source\repos\IFilterTextReader-master\IFilterTextReader-master\IFilterTextReader\FilterReader.cs:line 572
   at IFilterTextReader.FilterReader.ReadLine() in C:\Users\jbodker\source\repos\IFilterTextReader-master\IFilterTextReader-master\IFilterTextReader\FilterReader.cs:line 320
   at IFilterTextViewer.MainForm.SelectButton_Click(Object sender, EventArgs e) in C:\Users\jbodker\source\repos\IFilterTextReader-master\IFilterTextReader-master\IFilterTextViewer\MainForm.cs:line 149
Index was outside the bounds of the array.`

For some reason the `textLength` is 0 in line 572 in the FilterReader thus making `textBuffer[textLength - 1]` blow up.

Best regards,
John

**Comment by Sicos1977** [comment]
Merged
